// ═══════════════════════════════════════════════════════════
//  PrediRoute — scenarios.js
//  Incident scenarios & route data per district
// ═══════════════════════════════════════════════════════════

const DISTRICTS = {
  4: {
    name: 'District 4 (Calibrated)',
    calibrated: true,
    routes: [
      {
        name: 'Zone Rouge (Red)',
        status: 'clear',
        statusLabel: 'Clear',
        predicted: '0.8%',
        predClass: 'low-cong',
        risk: 'low',
        riskLabel: 'Low',
        action: 'maintain',
        actionLabel: 'Maintain',
      },
      {
        name: 'Ring Road',
        status: 'jam',
        statusLabel: 'Jam (Synthetic)',
        predicted: '99.4%',
        predClass: 'high-cong',
        risk: 'critical',
        riskLabel: 'Critical',
        action: 'reroute',
        actionLabel: 'Reroute',
      },
      {
        name: 'Dense Urban',
        status: 'slow',
        statusLabel: 'Slow',
        predicted: '38.9%',
        predClass: 'mid-cong',
        risk: 'high',
        riskLabel: 'High',
        action: 'prepare-reroute',
        actionLabel: 'Prepare Reroute',
      },
      {
        name: 'Highway',
        status: 'normal',
        statusLabel: 'Normal',
        predicted: '1.4%',
        predClass: 'normal-cong',
        risk: 'normal',
        riskLabel: 'Normal',
        action: 'monitor',
        actionLabel: 'Monitor',
      },
    ],
    router: {
      hasIncident: true,
      incidentDesc: 'Ring Road Accident detected',
      incidentSub: '(Synthetic Stress Test – Flow ×3.5)',
      currentRoute: 'Ring Road',
      currentETA: '29.8 min',
      currentCong: '99.4%',
      currentCongClass: 'red',
      recRoute: 'Highway',
      recETA: '6.7 min',
      recCong: '0.6%',
      recCongClass: 'green',
      timeSaved: '23.1 minutes',
      confidence: '99%',
      justification: 'Route changed due to estimated time gain exceeding the 3-minute threshold (Gain = 23.1 min). Hourly calibration applied (Coef 08h = 1.10). No data leakage from test set.',
    },
    kpi: {
      vehicles: '12 <small>units</small>',
      fuel: '14% <small>≈ 1.2L</small>',
      co2: '≈ 3.2 kg <small>(Fuel × 2.68)</small>',
      cost: '≈ $2.45 <small>(This Trip)</small>',
    },
    alerts: [
      { time: '07:58 AM', tag: 'accident', title: 'Ring Road Accident (Synthetic)', sub: 'Flow multiplier: ×3.5', dot: 'red' },
      { time: '07:45 AM', tag: 'jam',      title: 'Dense Urban Slowdown',           sub: 'Congestion building up',  dot: 'orange' },
      { time: '07:30 AM', tag: 'roadworks',title: 'Zone Rouge Maintenance',          sub: 'Minor impact expected',   dot: 'blue' },
      { time: '07:15 AM', tag: 'clear',    title: 'Highway Clear',                   sub: 'Normal traffic conditions',dot: 'green' },
    ],
  },

  7: {
    name: 'District 7',
    calibrated: false,
    routes: [
      {
        name: 'North Corridor',
        status: 'clear',
        statusLabel: 'Clear',
        predicted: '2.1%',
        predClass: 'low-cong',
        risk: 'low',
        riskLabel: 'Low',
        action: 'maintain',
        actionLabel: 'Maintain',
      },
      {
        name: 'Central Ave',
        status: 'slow',
        statusLabel: 'Slow',
        predicted: '44.2%',
        predClass: 'mid-cong',
        risk: 'high',
        riskLabel: 'High',
        action: 'prepare-reroute',
        actionLabel: 'Prepare Reroute',
      },
      {
        name: 'East Bypass',
        status: 'jam',
        statusLabel: 'Jam',
        predicted: '71.5%',
        predClass: 'high-cong',
        risk: 'critical',
        riskLabel: 'Critical',
        action: 'reroute',
        actionLabel: 'Reroute',
      },
      {
        name: 'Outer Ring',
        status: 'normal',
        statusLabel: 'Normal',
        predicted: '5.3%',
        predClass: 'normal-cong',
        risk: 'normal',
        riskLabel: 'Normal',
        action: 'monitor',
        actionLabel: 'Monitor',
      },
    ],
    router: {
      hasIncident: false,
      incidentDesc: '',
      incidentSub: '',
      currentRoute: 'East Bypass',
      currentETA: '18.4 min',
      currentCong: '71.5%',
      currentCongClass: 'red',
      recRoute: 'Outer Ring',
      recETA: '9.2 min',
      recCong: '5.3%',
      recCongClass: 'green',
      timeSaved: '9.2 minutes',
      confidence: '87%',
      justification: 'Route changed due to estimated time gain exceeding the 3-minute threshold (Gain = 9.2 min). No calibration applied (District 7 uncalibrated to preserve 100% accident detection).',
    },
    kpi: {
      vehicles: '8 <small>units</small>',
      fuel: '9% <small>≈ 0.8L</small>',
      co2: '≈ 2.1 kg <small>(Fuel × 2.68)</small>',
      cost: '≈ $1.60 <small>(This Trip)</small>',
    },
    alerts: [
      { time: '07:52 AM', tag: 'jam',      title: 'East Bypass Congestion',    sub: 'Heavy traffic buildup',       dot: 'orange' },
      { time: '07:38 AM', tag: 'roadworks',title: 'Central Ave Works',          sub: 'Lane reduction active',       dot: 'blue' },
      { time: '07:20 AM', tag: 'clear',    title: 'Outer Ring Free Flow',       sub: 'Normal traffic conditions',   dot: 'green' },
      { time: '07:05 AM', tag: 'clear',    title: 'North Corridor Clear',       sub: 'No incidents reported',       dot: 'green' },
    ],
  },

  11: {
    name: 'District 11',
    calibrated: false,
    routes: [
      {
        name: 'Boulevard Sud',
        status: 'clear',
        statusLabel: 'Clear',
        predicted: '1.3%',
        predClass: 'low-cong',
        risk: 'low',
        riskLabel: 'Low',
        action: 'maintain',
        actionLabel: 'Maintain',
      },
      {
        name: 'Industrial Link',
        status: 'slow',
        statusLabel: 'Slow',
        predicted: '29.7%',
        predClass: 'mid-cong',
        risk: 'high',
        riskLabel: 'High',
        action: 'prepare-reroute',
        actionLabel: 'Prepare Reroute',
      },
      {
        name: 'Tunnel Route',
        status: 'jam',
        statusLabel: 'Jam',
        predicted: '88.6%',
        predClass: 'high-cong',
        risk: 'critical',
        riskLabel: 'Critical',
        action: 'reroute',
        actionLabel: 'Reroute',
      },
      {
        name: 'Coastal Road',
        status: 'normal',
        statusLabel: 'Normal',
        predicted: '3.8%',
        predClass: 'normal-cong',
        risk: 'normal',
        riskLabel: 'Normal',
        action: 'monitor',
        actionLabel: 'Monitor',
      },
    ],
    router: {
      hasIncident: false,
      incidentDesc: '',
      incidentSub: '',
      currentRoute: 'Tunnel Route',
      currentETA: '24.1 min',
      currentCong: '88.6%',
      currentCongClass: 'red',
      recRoute: 'Coastal Road',
      recETA: '11.3 min',
      recCong: '3.8%',
      recCongClass: 'green',
      timeSaved: '12.8 minutes',
      confidence: '91%',
      justification: 'Route changed due to Tunnel Route jam exceeding critical threshold. Coastal Road offers clear flow. No calibration applied (District 11 uncalibrated to preserve 100% accident detection).',
    },
    kpi: {
      vehicles: '15 <small>units</small>',
      fuel: '11% <small>≈ 1.0L</small>',
      co2: '≈ 2.7 kg <small>(Fuel × 2.68)</small>',
      cost: '≈ $1.95 <small>(This Trip)</small>',
    },
    alerts: [
      { time: '07:55 AM', tag: 'jam',      title: 'Tunnel Route Blocked',      sub: 'Incident under investigation',dot: 'red' },
      { time: '07:40 AM', tag: 'roadworks',title: 'Industrial Link Delays',     sub: 'Scheduled maintenance',       dot: 'blue' },
      { time: '07:25 AM', tag: 'clear',    title: 'Coastal Road Open',          sub: 'Good conditions ahead',       dot: 'green' },
      { time: '07:10 AM', tag: 'clear',    title: 'Boulevard Sud Normal',       sub: 'Light traffic',               dot: 'green' },
    ],
  },
};

// Map route colors per district
const MAP_COLORS = {
  4: {
    routes: [
      { id: 'route-zone-rouge', color: '#22c55e' },
      { id: 'route-ring-road',  color: '#ef4444' },
      { id: 'route-dense-urban',color: '#f97316' },
      { id: 'route-highway',    color: '#22c55e' },
    ],
    labels: [
      { rectId: null, x: 290, y: 62,  w: 92,  h: 26, color: '#ef4444', text: 'Ring Road 99.4%',     tx: 336, ty: 79  },
      { rectId: null, x: 225, y: 190, w: 102, h: 26, color: '#f97316', text: 'Dense Urban 38.9%',   tx: 276, ty: 207 },
      { rectId: null, x: 410, y: 325, w: 90,  h: 26, color: '#22c55e', text: 'Highway 1.4%',         tx: 455, ty: 342 },
      { rectId: null, x: 15,  y: 328, w: 110, h: 26, color: '#22c55e', text: 'Zone Rouge 0.8%',      tx: 70,  ty: 345 },
    ],
  },
  7: {
    routes: [
      { id: 'route-zone-rouge', color: '#22c55e' },
      { id: 'route-ring-road',  color: '#f97316' },
      { id: 'route-dense-urban',color: '#ef4444' },
      { id: 'route-highway',    color: '#22c55e' },
    ],
    labels: [
      { x: 290, y: 62,  w: 102, h: 26, color: '#f97316', text: 'Central Ave 44.2%',  tx: 341, ty: 79  },
      { x: 225, y: 190, w: 102, h: 26, color: '#ef4444', text: 'East Bypass 71.5%',  tx: 276, ty: 207 },
      { x: 410, y: 325, w: 100, h: 26, color: '#22c55e', text: 'Outer Ring 5.3%',    tx: 460, ty: 342 },
      { x: 15,  y: 328, w: 112, h: 26, color: '#22c55e', text: 'N. Corridor 2.1%',   tx: 71,  ty: 345 },
    ],
  },
  11: {
    routes: [
      { id: 'route-zone-rouge', color: '#22c55e' },
      { id: 'route-ring-road',  color: '#ef4444' },
      { id: 'route-dense-urban',color: '#f97316' },
      { id: 'route-highway',    color: '#22c55e' },
    ],
    labels: [
      { x: 280, y: 62,  w: 110, h: 26, color: '#ef4444', text: 'Tunnel Rt. 88.6%',  tx: 335, ty: 79  },
      { x: 220, y: 190, w: 108, h: 26, color: '#f97316', text: 'Indust. Lk 29.7%',  tx: 274, ty: 207 },
      { x: 400, y: 325, w: 110, h: 26, color: '#22c55e', text: 'Coastal Rd 3.8%',   tx: 455, ty: 342 },
      { x: 15,  y: 328, w: 112, h: 26, color: '#22c55e', text: 'Boul. Sud 1.3%',    tx: 71,  ty: 345 },
    ],
  },
};
